language: generic
sudo: required
services: 
  - docker


before_install:
  - docker build -t praveenvisva/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true praveenvisva/docker-react npm run test
  


